apiVersion: v1
kind: Service
metadata:
  name: tienda
  labels:
    app: tienda
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: tienda
  type: LoadBalancer  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tienda
  labels:
    app: tienda
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tienda
    spec:
      containers:
      - image: joyapu.azurecr.io/tienda
        name: tienda
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: 900m
          requests:
            cpu: 100m
      imagePullSecrets:
        - name: regsecret
---      
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tienda
spec:
  scaleTargetRef:
    kind: Deployment
    name: tienda
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
