apiVersion: v1
kind: Service
metadata:
  name: phpappcontainer
  labels:
    app: phpappcontainer
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: phpappcontainer
  type: LoadBalancer  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: phpappcontainer
  labels:
    app: phpappcontainer
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: phpappcontainer
    spec:
      containers:
      - image: joyapu.azurecr.io/phpappcontainer
        name: phpappcontainer
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: 900m
          requests:
            cpu: 100m
      imagePullSecrets:
        - name: regsecret
---      
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: phpappcontainer
spec:
  scaleTargetRef:
    kind: Deployment
    name: phpappcontainer
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
