---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: vistamicroservices
  namespace: default
  selfLink: "/apis/extensions/v1beta1/namespaces/default/deployments/vistamicroservices"
  uid: 218e733d-edf0-11e8-996a-96629458d2eb
  resourceVersion: '23407107'
  generation: 46
  creationTimestamp: '2018-11-22T00:47:04Z'
  labels:
    app: vistamicroservices
  annotations:
    deployment.kubernetes.io/revision: '8'
spec:
  replicas: 25
  selector:
    matchLabels:
      app: vistamicroservices
  template:
    metadata:
      creationTimestamp: 
      labels:
        app: vistamicroservices
    spec:
      containers:
      - name: vistamicroservices
        image: acreucdcprd01.azurecr.io/vistamicroservices:e13e67b08b31bd1e52708da0bf46bbb6aad68cdb
        ports:
        - name: http
          containerPort: 8083
          protocol: TCP
        resources: {}
        readinessProbe:
          httpGet:
            path: "/"
            port: 8083
            scheme: HTTP
          initialDelaySeconds: 55
          timeoutSeconds: 60
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
      - name: regsecret
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 46
  replicas: 25
  updatedReplicas: 25
  readyReplicas: 25
  availableReplicas: 25
  conditions:
  - type: Progressing
    status: 'True'
    lastUpdateTime: '2019-04-01T03:40:16Z'
    lastTransitionTime: '2018-11-22T00:47:04Z'
    reason: NewReplicaSetAvailable
    message: ReplicaSet "vistamicroservices-6d4f9f875d" has successfully progressed.
  - type: Available
    status: 'True'
    lastUpdateTime: '2019-04-02T18:35:03Z'
    lastTransitionTime: '2019-04-02T18:35:03Z'
    reason: MinimumReplicasAvailable
    message: Deployment has minimum availability.
